modLoader="javafml"
loaderVersion="[43,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/skyjay1/GreekFantasy/issues"

[[mods]]
    modId="greekfantasy"
    version="19.2.1"
    displayName="Greek Fantasy"
    credits=""
    authors="skyjay1"
    description='''Get your Greek on!'''

    [[dependencies.greekfantasy]]
        modId="forge"
        mandatory=true
        versionRange="[43.1,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.greekfantasy]]
        modId="rpggods"
        mandatory=false
        versionRange="[19.2,)"
        ordering="AFTER"
        side="BOTH"
